In [427]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\heram\anaconda3\lib\site-packages (4.21.0)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\heram\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (2.0.7)
Requirement already satisfied: trio~=0.17 in c:\users\heram\anaconda3\lib\site-packages (from selenium) (0.25.1)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\heram\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\heram\anaconda3\lib\site-packages (from selenium) (2024.2.2)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\heram\anaconda3\lib\site-packages (from selenium) (4.9.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\heram\anaconda3\lib\site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in c:\users\heram\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\heram\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\heram\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\heram\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\heram\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.16.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\heram\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\heram\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\heram\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\heram\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [428]:
# Importing librarires
import selenium
import pandas as pd
import numpy as np
import time


# Importing selenium webdriver
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.common.exceptions import ElementNotInteractableException

# importing requests
import requests

from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

## lets scrape for Las Vegas

In [429]:
 driver = webdriver.Chrome()
driver.maximize_window()

In [430]:
driver.get("https://homefinder.com/")
time.sleep(2)  # Wait for the page to load

In [431]:
search_location=driver.find_element(By.XPATH,"/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/input") 
search_location.send_keys("Las Vegas, NV")

In [432]:
click_tab= driver.find_element(By.XPATH,'/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/div[2]/button/span')
click_tab.click()
time.sleep(3)

In [433]:
# fetching url to open each jobs
estate_url = []
start=0
end=5
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    li_index = 3 + page
    next_button_xpath = f'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[{li_index}]/a'
    next_button = driver.find_element(By.XPATH, next_button_xpath)
    next_button.click()   
    time.sleep(4)

In [434]:
# fetching url to open each jobs
start=0
end=10
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    
    
    next_button = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[7]/a')
    next_button.click()
    time.sleep(4)

In [435]:
Bhk = []
Bed = []
Property_Type = []
Bathroom = []
Address = []
City = []
State_code = []
Country = []
Landmark = []
Year_Built = []
Price_per_sqft  = []
Buy_total_price = []
Carpetarea = []

for i in estate_url:
    driver.get(i)
    time.sleep(3)
    
    try:
        bhk_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bhk.append(bhk_detail.text[0:1])
    except NoSuchElementException:
        Bhk.append(np.nan)
        

    try:
        bed_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bed.append(bed_detail.text[0:1])
    except NoSuchElementException:
        Bed.append(np.nan)

    
    try:
        prop_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[2]/p')
        Property_Type.append(prop_detail.text)      
    except NoSuchElementException:
        Property_Type.append(np.nan)
        
    try:
        bathroom_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[2]')
        Bathroom.append(bathroom_detail.text[0:1])
    except NoSuchElementException:
        Bathroom.append(np.nan)
        
    try:
        add_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1')
        Address.append(add_detail.text)
    except NoSuchElementException:
        Address.append(np.nan)
    
    try:
        city_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        City.append(city_detail.text[0:9])
    except NoSuchElementException:
        City.append(np.nan)

    try:
        state_details = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        State_code.append(state_details.text[-8:-6])
    except NoSuchElementException:
        State_code.append(np.nan)

    
    try:
        landmark = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[5]/div/div[1]/div/table/tbody/tr[1]/td[1]')
        Landmark.append(landmark.text)
    except NoSuchElementException:
        Landmark.append(np.nan)

    try:
        year = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[9]/div/div[2]')
        Year_Built.append(year.text)       
    except NoSuchElementException:
        Year_Built.append(np.nan)
        
    try:
        psq = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[8]/div/div[2]')
        Price_per_sqft.append(psq.text)
    except NoSuchElementException:
        Price_per_sqft.append(np.nan)
        
    try:
        total = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[2]/div/div[1]/p[2]')
        Buy_total_price.append(total.text[:-24])
    except NoSuchElementException:
        Buy_total_price.append(np.nan)
    try:
        carpetarea = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[3]')
        Carpetarea.append(carpetarea.text)   
    except NoSuchElementException:
        Carpetarea.append(np.nan)

In [436]:
driver.close()

## Lets scrape for the city San Francisco

In [437]:
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://homefinder.com/")
time.sleep(2)  # Wait for the page to load

search_location=driver.find_element(By.XPATH,"/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/input") 
search_location.send_keys("San Francisco, CA")

click_tab= driver.find_element(By.XPATH,'/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/div[2]/button/span')
click_tab.click()      
time.sleep(3)

In [440]:
# fetching url to open each estate
estate_url = []
start=0
end=6
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    li_index = 3 + page
    next_button_xpath = f'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[{li_index}]/a'
    next_button = driver.find_element(By.XPATH, next_button_xpath)
    next_button.click()   
    time.sleep(4)

In [442]:
len(estate_url)

132

In [443]:
# fetching url to open each estate for further pages
start=0
end=9
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    
    
    next_button = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[7]/a')
    next_button.click()
    time.sleep(4)

In [444]:
for i in estate_url:
    driver.get(i)
    time.sleep(3)
    
    try:
        bhk_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bhk.append(bhk_detail.text[0:1])           
    except NoSuchElementException:
        Bhk.append(np.nan)
        

    try:
        bed_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bed.append(bed_detail.text[0:1])
    except NoSuchElementException:
        Bed.append(np.nan)

    
    try:
        prop_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[2]/p')
        Property_Type.append(prop_detail.text)      
    except NoSuchElementException:                 
        Property_Type.append(np.nan)
        
    try:
        bathroom_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[2]')
        Bathroom.append(bathroom_detail.text[0:1])
    except NoSuchElementException:
        Bathroom.append(np.nan)
        
    try:
        add_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1')
        Address.append(add_detail.text)            
    except NoSuchElementException:
        Address.append(np.nan)
        
    try:
        city_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        City.append(city_detail.text[0:13])
    except NoSuchElementException:
        City.append(np.nan)
        
    try:
        state_details = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        State_code.append(state_details.text[-8:-6])
    except NoSuchElementException:
        State_code.append(np.nan)

    
    try:
        landmark = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[5]/div/div[1]/div/table/tbody/tr[1]/td[1]')
        Landmark.append(landmark.text)
    except NoSuchElementException:
        Landmark.append(np.nan)

    try:
        year = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[8]/div/div[2]')
        Year_Built.append(year.text)        
    except NoSuchElementException:
        Year_Built.append(np.nan)
        
    try:
        psq = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[7]/div/div[2]')
        Price_per_sqft.append(psq.text)
    except NoSuchElementException:
        Price_per_sqft.append(np.nan)
        
    try:
        total = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[2]/div/div[1]/p[2]')
        Buy_total_price.append(total.text[:-24])
    except NoSuchElementException:
        Buy_total_price.append(np.nan)
    try:
        carpetarea = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[3]')
        Carpetarea.append(carpetarea.text)
    except NoSuchElementException:
        Carpetarea.append(np.nan)

In [446]:
driver.close()

## lets scrape the data for Washington, DC

In [448]:
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://homefinder.com/")
time.sleep(2)  # Wait for the page to load

search_location=driver.find_element(By.XPATH,"/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/input") 
search_location.send_keys("Washington, DC")

click_tab= driver.find_element(By.XPATH,'/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/div[2]/button/span')
click_tab.click()      
time.sleep(3)

In [449]:
# fetching url to open each estate
estate_url = []
start=0
end=6
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    li_index = 3 + page
    next_button_xpath = f'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[{li_index}]/a'
    next_button = driver.find_element(By.XPATH, next_button_xpath)
    next_button.click()   
    time.sleep(4)

In [450]:
# fetching url to open each estate for further pages
start=0
end=10
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    
    
    next_button = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[7]/a')
    next_button.click()
    time.sleep(4)

In [451]:
len(estate_url)

352

In [452]:
for i in estate_url:
    driver.get(i)
    time.sleep(3)
    
    try:
        bhk_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bhk.append(bhk_detail.text[0:1])           
    except NoSuchElementException:
        Bhk.append(np.nan)
        

    try:
        bed_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bed.append(bed_detail.text[0:1])
    except NoSuchElementException:
        Bed.append(np.nan)

    
    try:
        prop_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[2]/p')
        Property_Type.append(prop_detail.text)      
    except NoSuchElementException:                 
        Property_Type.append(np.nan)
        
    try:
        bathroom_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[2]')
        Bathroom.append(bathroom_detail.text[0:1])
    except NoSuchElementException:
        Bathroom.append(np.nan)
        
    try:
        add_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1')
        Address.append(add_detail.text)            
    except NoSuchElementException:
        Address.append(np.nan)
        
    try:
        city_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        City.append(city_detail.text[0:10])
    except NoSuchElementException:
        City.append(np.nan)
        
    try:
        state_details = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        State_code.append(state_details.text[-8:-6])
    except NoSuchElementException:
        State_code.append(np.nan)

    
    try:
        landmark = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[5]/div/div[1]/div/table/tbody/tr[1]/td[1]')
        Landmark.append(landmark.text)
    except NoSuchElementException:
        Landmark.append(np.nan)

    try:
        year = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[7]/div/div[2]')
        Year_Built.append(year.text)        
    except NoSuchElementException:
        Year_Built.append(np.nan)
        
    try:
        psq = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[6]/div/div[2]')
        Price_per_sqft.append(psq.text)
    except NoSuchElementException:
        Price_per_sqft.append(np.nan)
        
    try:
        total = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[2]/div/div[1]/p[2]')
        Buy_total_price.append(total.text[:-24])
    except NoSuchElementException:
        Buy_total_price.append(np.nan)
    try:
        carpetarea = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[3]')
        Carpetarea.append(carpetarea.text)
    except NoSuchElementException:
        Carpetarea.append(np.nan)

In [460]:
driver.close()

## lets scrape the data for Miami, FL

In [461]:
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://homefinder.com/")
time.sleep(2)  # Wait for the page to load

search_location=driver.find_element(By.XPATH,"/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/input") 
search_location.send_keys("Miami, FL")

click_tab= driver.find_element(By.XPATH,'/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/div[2]/button/span')
click_tab.click()   
time.sleep(3)

In [462]:
# fetching url to open each estate
estate_url = []
start=0
end=6
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    li_index = 3 + page
    next_button_xpath = f'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[{li_index}]/a'
    next_button = driver.find_element(By.XPATH, next_button_xpath)
    next_button.click()   
    time.sleep(4)

In [463]:
# fetching url to open each estate for further pages
start=0
end=10
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    
    
    next_button = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[7]/a')
    next_button.click()
    time.sleep(4)

In [464]:
for i in estate_url:
    driver.get(i)
    time.sleep(3)
    
    try:
        bhk_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bhk.append(bhk_detail.text[0:1])           
    except NoSuchElementException:
        Bhk.append(np.nan)
        

    try:
        bed_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bed.append(bed_detail.text[0:1])
    except NoSuchElementException:
        Bed.append(np.nan)

    
    try:
        prop_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[2]/p')
        Property_Type.append(prop_detail.text[0:-9])      
    except NoSuchElementException:                 
        Property_Type.append(np.nan)
        
    try:
        bathroom_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[2]')
        Bathroom.append(bathroom_detail.text[0:1])
    except NoSuchElementException:
        Bathroom.append(np.nan)
        
    try:
        add_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1')
        Address.append(add_detail.text)            
    except NoSuchElementException:
        Address.append(np.nan)
        
    try:
        city_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        City.append(city_detail.text[0:5])
    except NoSuchElementException:
        City.append(np.nan)
        
    try:
        state_details = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        State_code.append(state_details.text[-8:-6])
    except NoSuchElementException:
        State_code.append(np.nan)

    
    try:
        landmark = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[5]/div/div[1]/div/table/tbody/tr[1]/td[1]')
        Landmark.append(landmark.text)
    except NoSuchElementException:
        Landmark.append(np.nan)

    try:
        year = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[8]/div/div[2]')
        Year_Built.append(year.text)        
    except NoSuchElementException:
        Year_Built.append(np.nan)
        
    try:
        psq = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[7]/div/div[2]')
        Price_per_sqft.append(psq.text)
    except NoSuchElementException:
        Price_per_sqft.append(np.nan)
        
    try:
        total = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[2]/div/div[1]/p[2]')
        Buy_total_price.append(total.text[:-24])
    except NoSuchElementException:
        Buy_total_price.append(np.nan)
    try:
        carpetarea = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[3]')
        Carpetarea.append(carpetarea.text)
    except NoSuchElementException:
        Carpetarea.append(np.nan)

In [467]:
driver.close()

## lets scrape the data for Chicago, IL

In [468]:
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://homefinder.com/")
time.sleep(2)  # Wait for the page to load

search_location=driver.find_element(By.XPATH,"/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/input") 
search_location.send_keys("Chicago, IL")

click_tab= driver.find_element(By.XPATH,'/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/div[2]/button/span')
click_tab.click()
time.sleep(3)

In [469]:
# fetching url to open each estate
estate_url = []
start=0
end=6
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    li_index = 3 + page
    next_button_xpath = f'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[{li_index}]/a'
    next_button = driver.find_element(By.XPATH, next_button_xpath)
    next_button.click()   
    time.sleep(4)

In [470]:
# fetching url to open each estate for further pages
start=0
end=10
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    
    
    next_button = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[7]/a')
    next_button.click()
    time.sleep(4)

In [471]:
for i in estate_url:
    driver.get(i)
    time.sleep(3)
    
    try:
        bhk_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bhk.append(bhk_detail.text[0:1])           
    except NoSuchElementException:
        Bhk.append(np.nan)
        

    try:
        bed_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bed.append(bed_detail.text[0:1])
    except NoSuchElementException:
        Bed.append(np.nan)

    
    try:
        prop_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[2]/p')
        Property_Type.append(prop_detail.text[0:-9])      
    except NoSuchElementException:                 
        Property_Type.append(np.nan)
        
    try:
        bathroom_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[2]')
        Bathroom.append(bathroom_detail.text[0:1])
    except NoSuchElementException:
        Bathroom.append(np.nan)
        
    try:
        add_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1')
        Address.append(add_detail.text)            
    except NoSuchElementException:
        Address.append(np.nan)
        
    try:
        city_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        City.append(city_detail.text[0:7])
    except NoSuchElementException:
        City.append(np.nan)
        
    try:
        state_details = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        State_code.append(state_details.text[-8:-6])
    except NoSuchElementException:
        State_code.append(np.nan)

    
    try:
        landmark = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[5]/div/div[1]/div/table/tbody/tr[1]/td[1]')
        Landmark.append(landmark.text)
    except NoSuchElementException:
        Landmark.append(np.nan)

    try:
        year = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[8]/div/div[2]')
        Year_Built.append(year.text)        
    except NoSuchElementException:
        Year_Built.append(np.nan)

    
    try:
        psq = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[7]/div/div[2]')
        Price_per_sqft.append(psq.text)
    except NoSuchElementException:
        Price_per_sqft.append(np.nan)
        
    try:
        total = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[2]/div/div[1]/p[2]')
        Buy_total_price.append(total.text[:-24])
    except NoSuchElementException:
        Buy_total_price.append(np.nan)
    try:
        carpetarea = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[3]')
        Carpetarea.append(carpetarea.text)
    except NoSuchElementException:
        Carpetarea.append(np.nan)

In [472]:
driver.close()

## lets scrape the data for Houston, TX

In [473]:
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://homefinder.com/")
time.sleep(2)  # Wait for the page to load

search_location=driver.find_element(By.XPATH,"/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/input") 
search_location.send_keys("Houston, TX")

click_tab= driver.find_element(By.XPATH,'/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/div[2]/button/span')
click_tab.click()      
time.sleep(3)

In [474]:
# fetching url to open each estate
estate_url = []
start=0
end=6
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    li_index = 3 + page
    next_button_xpath = f'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[{li_index}]/a'
    next_button = driver.find_element(By.XPATH, next_button_xpath)
    next_button.click()   
    time.sleep(4)

In [475]:
# fetching url to open each estate for further pages
start=0
end=5
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    
    
    next_button = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[7]/a')
    next_button.click()
    time.sleep(4)

In [476]:
for i in estate_url:
    driver.get(i)
    time.sleep(3)
    
    try:
        bhk_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bhk.append(bhk_detail.text[0:1])           
    except NoSuchElementException:
        Bhk.append(np.nan)
        

    try:
        bed_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bed.append(bed_detail.text[0:1])
    except NoSuchElementException:
        Bed.append(np.nan)

    
    try:
        prop_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[2]/p')
        Property_Type.append(prop_detail.text[0:-9])      
    except NoSuchElementException:                 
        Property_Type.append(np.nan)
        
    try:
        bathroom_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[2]')
        Bathroom.append(bathroom_detail.text[0:1])
    except NoSuchElementException:
        Bathroom.append(np.nan)
        
    try:
        add_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1')
        Address.append(add_detail.text)            
    except NoSuchElementException:
        Address.append(np.nan)
        
    try:
        city_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        City.append(city_detail.text[0:7])
    except NoSuchElementException:
        City.append(np.nan)
        
    try:
        state_details = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        State_code.append(state_details.text[-8:-6])
    except NoSuchElementException:
        State_code.append(np.nan)

    
    try:
        landmark = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[5]/div/div[1]/div/table/tbody/tr[1]/td[1]')
        Landmark.append(landmark.text)
    except NoSuchElementException:
        Landmark.append(np.nan)

    try:
        year = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[7]/div/div[2]')
        Year_Built.append(year.text)        
    except NoSuchElementException:
        Year_Built.append(np.nan)

    
    try:
        psq = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[6]/div/div[2]')
        Price_per_sqft.append(psq.text)
    except NoSuchElementException:
        Price_per_sqft.append(np.nan)
        
    try:
        total = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[2]/div/div[1]/p[2]')
        Buy_total_price.append(total.text[:-24])
    except NoSuchElementException:
        Buy_total_price.append(np.nan)
    try:
        carpetarea = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[3]')
        Carpetarea.append(carpetarea.text)
    except NoSuchElementException:
        Carpetarea.append(np.nan)

In [477]:
driver.close()

## lets scrape the data for Los Angeles, CA

In [478]:
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://homefinder.com/")
time.sleep(2)  # Wait for the page to load

search_location=driver.find_element(By.XPATH,"/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/input") 
search_location.send_keys("Los Angeles, CA")

click_tab= driver.find_element(By.XPATH,'/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/div[2]/button/span')
click_tab.click()      
time.sleep(3)

In [479]:
# fetching url to open each estate
estate_url = []
start=0
end=6
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    li_index = 3 + page
    next_button_xpath = f'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[{li_index}]/a'
    next_button = driver.find_element(By.XPATH, next_button_xpath)
    next_button.click()   
    time.sleep(4)

In [480]:
# fetching url to open each estate for further pages
start=0
end=10
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    
    
    next_button = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[7]/a')
    next_button.click()
    time.sleep(4)

In [481]:
for i in estate_url:
    driver.get(i)
    time.sleep(3)
    
    try:
        bhk_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bhk.append(bhk_detail.text[0:1])           
    except NoSuchElementException:
        Bhk.append(np.nan)
        

    try:
        bed_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bed.append(bed_detail.text[0:1])
    except NoSuchElementException:
        Bed.append(np.nan)

    
    try:
        prop_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[2]/p')
        Property_Type.append(prop_detail.text[0:-9])      
    except NoSuchElementException:                 
        Property_Type.append(np.nan)
        
    try:
        bathroom_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[2]')
        Bathroom.append(bathroom_detail.text[0:1])
    except NoSuchElementException:
        Bathroom.append(np.nan)
        
    try:
        add_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1')
        Address.append(add_detail.text)            
    except NoSuchElementException:
        Address.append(np.nan)
        
    try:
        city_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        City.append(city_detail.text[0:11])
    except NoSuchElementException:
        City.append(np.nan)
        
    try:
        state_details = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        State_code.append(state_details.text[-8:-6])
    except NoSuchElementException:
        State_code.append(np.nan)

    
    try:
        landmark = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[5]/div/div[1]/div/table/tbody/tr[1]/td[1]')
        Landmark.append(landmark.text)
    except NoSuchElementException:
        Landmark.append(np.nan)

    try:
        year = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[9]/div/div[2]')
        Year_Built.append(year.text)        
    except NoSuchElementException:
        Year_Built.append(np.nan)

    
    try:
        psq = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[8]/div/div[2]')
        Price_per_sqft.append(psq.text)
    except NoSuchElementException:
        Price_per_sqft.append(np.nan)
        
    try:
        total = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[2]/div/div[1]/p[2]')
        Buy_total_price.append(total.text[:-24])
    except NoSuchElementException:
        Buy_total_price.append(np.nan)
    try:
        carpetarea = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[3]')
        Carpetarea.append(carpetarea.text)
    except NoSuchElementException:
        Carpetarea.append(np.nan)

In [482]:
driver.close()

## Lets scrape the data for Phoenix, AZ

In [483]:
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://homefinder.com/")
time.sleep(2)  # Wait for the page to load

search_location=driver.find_element(By.XPATH,"/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/input") 
search_location.send_keys("Phoenix, AZ")

click_tab= driver.find_element(By.XPATH,'/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/div[2]/button/span')
click_tab.click()     
time.sleep(3)

In [484]:
# fetching url to open each estate
estate_url = []
start=0
end=6
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    li_index = 3 + page
    next_button_xpath = f'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[{li_index}]/a'
    next_button = driver.find_element(By.XPATH, next_button_xpath)
    next_button.click()   
    time.sleep(4)

In [485]:
# fetching url to open each estate for further pages
start=0
end=10
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    
    
    next_button = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[7]/a')
    next_button.click()
    time.sleep(4)

In [486]:
for i in estate_url:
    driver.get(i)
    time.sleep(3)
    
    try:
        bhk_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bhk.append(bhk_detail.text[0:1])           
    except NoSuchElementException:
        Bhk.append(np.nan)
        

    try:
        bed_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bed.append(bed_detail.text[0:1])
    except NoSuchElementException:
        Bed.append(np.nan)

    
    try:
        prop_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[2]/p')
        Property_Type.append(prop_detail.text[0:-9])      
    except NoSuchElementException:                 
        Property_Type.append(np.nan)
        
    try:
        bathroom_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[2]')
        Bathroom.append(bathroom_detail.text[0:1])
    except NoSuchElementException:
        Bathroom.append(np.nan)
        
    try:
        add_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1')
        Address.append(add_detail.text)            
    except NoSuchElementException:
        Address.append(np.nan)
        
    try:
        city_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        City.append(city_detail.text[0:7])
    except NoSuchElementException:
        City.append(np.nan)
        
    try:
        state_details = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        State_code.append(state_details.text[-8:-6])
    except NoSuchElementException:
        State_code.append(np.nan)

    
    try:
        landmark = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[5]/div/div[1]/div/table/tbody/tr[1]/td[1]')
        Landmark.append(landmark.text)
    except NoSuchElementException:
        Landmark.append(np.nan)

    try:
        year = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[9]/div/div[2]')
        Year_Built.append(year.text)        
    except NoSuchElementException:
        Year_Built.append(np.nan)

    
    try:
        psq = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[8]/div/div[2]')
        Price_per_sqft.append(psq.text)
    except NoSuchElementException:
        Price_per_sqft.append(np.nan)
        
    try:
        total = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[2]/div/div[1]/p[2]')
        Buy_total_price.append(total.text[:-24])
    except NoSuchElementException:
        Buy_total_price.append(np.nan)
    try:
        carpetarea = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[3]')
        Carpetarea.append(carpetarea.text)
    except NoSuchElementException:
        Carpetarea.append(np.nan)

In [487]:
driver.close()

In [497]:
City.count("Indianapolis")

29

## lets scrape the data for Indianapolis, IN

In [500]:
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://homefinder.com/")
time.sleep(2)  # Wait for the page to load

search_location=driver.find_element(By.XPATH,"/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/input") 
search_location.send_keys("Indianapolis, IN")

click_tab= driver.find_element(By.XPATH,'/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/div[2]/button/span')
click_tab.click()    
time.sleep(3)

In [501]:
# fetching url to open each estate
estate_url = []
start=0
end=6
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    li_index = 3 + page
    next_button_xpath = f'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[{li_index}]/a'
    next_button = driver.find_element(By.XPATH, next_button_xpath)
    next_button.click()   
    time.sleep(4)

In [502]:
# fetching url to open each estate for further pages
start=0
end=15
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    
    
    next_button = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[7]/a')
    next_button.click()
    time.sleep(4)

In [503]:
len(estate_url)

462

In [504]:
for i in estate_url:
    driver.get(i)
    time.sleep(3)
    
    try:
        bhk_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bhk.append(bhk_detail.text[0:1])           
    except NoSuchElementException:
        Bhk.append(np.nan)
        

    try:
        bed_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bed.append(bed_detail.text[0:1])
    except NoSuchElementException:
        Bed.append(np.nan)

    
    try:
        prop_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[2]/p')
        Property_Type.append(prop_detail.text[0:-9])      
    except NoSuchElementException:                 
        Property_Type.append(np.nan)
        
    try:
        bathroom_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[2]')
        Bathroom.append(bathroom_detail.text[0:1])
    except NoSuchElementException:
        Bathroom.append(np.nan)
        
    try:
        add_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1')
        Address.append(add_detail.text)            
    except NoSuchElementException:
        Address.append(np.nan)
        
    try:
        city_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        City.append(city_detail.text[0:12])
    except NoSuchElementException:
        City.append(np.nan)
        
    try:
        state_details = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        State_code.append(state_details.text[-8:-6])
    except NoSuchElementException:
        State_code.append(np.nan)

    
    try:
        landmark = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[5]/div/div[1]/div/table/tbody/tr[1]/td[1]')
        Landmark.append(landmark.text)
    except NoSuchElementException:
        Landmark.append(np.nan)

    try:
        year = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[8]/div/div[2]')
        Year_Built.append(year.text)        
    except NoSuchElementException:
        Year_Built.append(np.nan)

    
    try:
        psq = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[7]/div/div[2]')
        Price_per_sqft.append(psq.text)
    except NoSuchElementException:
        Price_per_sqft.append(np.nan)
        
    try:
        total = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[2]/div/div[1]/p[2]')
        Buy_total_price.append(total.text[:-24])
    except NoSuchElementException:
        Buy_total_price.append(np.nan)
    try:
        carpetarea = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[3]')
        Carpetarea.append(carpetarea.text)
    except NoSuchElementException:
        Carpetarea.append(np.nan)

In [505]:
driver.close()

## Lets scrape the data for Columbus, OH

In [506]:
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://homefinder.com/")
time.sleep(2)  # Wait for the page to load

search_location=driver.find_element(By.XPATH,"/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/input") 
search_location.send_keys("Columbus, OH")

click_tab= driver.find_element(By.XPATH,'/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/div[2]/button/span')
click_tab.click()   
time.sleep(3)

In [507]:
# fetching url to open each estate
estate_url = []
start=0
end=6
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    li_index = 3 + page
    next_button_xpath = f'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[{li_index}]/a'
    next_button = driver.find_element(By.XPATH, next_button_xpath)
    next_button.click()   
    time.sleep(4)

In [508]:
# fetching url to open each estate for further pages
start=0
end=15
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    
    
    next_button = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[7]/a')
    next_button.click()
    time.sleep(4)

In [509]:
for i in estate_url:
    driver.get(i)
    time.sleep(3)
    
    try:
        bhk_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bhk.append(bhk_detail.text[0:1])           
    except NoSuchElementException:
        Bhk.append(np.nan)
        

    try:
        bed_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bed.append(bed_detail.text[0:1])
    except NoSuchElementException:
        Bed.append(np.nan)

    
    try:
        prop_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[2]/p')
        Property_Type.append(prop_detail.text[0:-9])      
    except NoSuchElementException:                 
        Property_Type.append(np.nan)
        
    try:
        bathroom_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[2]')
        Bathroom.append(bathroom_detail.text[0:1])
    except NoSuchElementException:
        Bathroom.append(np.nan)
        
    try:
        add_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1')
        Address.append(add_detail.text)            
    except NoSuchElementException:
        Address.append(np.nan)
        
    try:
        city_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        City.append(city_detail.text[0:8])
    except NoSuchElementException:
        City.append(np.nan)
        
    try:
        state_details = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        State_code.append(state_details.text[-8:-6])
    except NoSuchElementException:
        State_code.append(np.nan)

    
    try:
        landmark = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[5]/div/div[1]/div/table/tbody/tr[1]/td[1]')
        Landmark.append(landmark.text)
    except NoSuchElementException:
        Landmark.append(np.nan)

    try:
        year = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[8]/div/div[2]')
        Year_Built.append(year.text)        
    except NoSuchElementException:
        Year_Built.append(np.nan)

    
    try:
        psq = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[7]/div/div[2]')
        Price_per_sqft.append(psq.text)
    except NoSuchElementException:
        Price_per_sqft.append(np.nan)
        
    try:
        total = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[2]/div/div[1]/p[2]')
        Buy_total_price.append(total.text[:-24])
    except NoSuchElementException:
        Buy_total_price.append(np.nan)
    try:
        carpetarea = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[3]')
        Carpetarea.append(carpetarea.text)
    except NoSuchElementException:
        Carpetarea.append(np.nan)

In [510]:
driver.close()

## lets scrape the data for San Antonio, TX

In [511]:
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://homefinder.com/")
time.sleep(2)  # Wait for the page to load

search_location=driver.find_element(By.XPATH,"/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/input") 
search_location.send_keys("San Antonio, TX")

click_tab= driver.find_element(By.XPATH,'/html/body/div/div/div/div/section/div/header/div/div/div/form/div/div[1]/div/div/div[2]/button/span')
click_tab.click()   
time.sleep(3)

In [512]:
# fetching url to open each estate
estate_url = []
start=0
end=6
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    li_index = 3 + page
    next_button_xpath = f'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[{li_index}]/a'
    next_button = driver.find_element(By.XPATH, next_button_xpath)
    next_button.click()   
    time.sleep(4)

In [513]:
# fetching url to open each estate for further pages
start=0
end=10
for page in range(start,end):
    url= driver.find_elements(By.XPATH,'//div[@class="results-items mt-2"]/div/a')
    for i in url:
        estate_url.append(i.get_attribute('href')) # to retrieve any link we use get_attribute
    
    
    next_button = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[1]/div[4]/div[1]/div[3]/nav/ul/li[7]/a')
    next_button.click()
    time.sleep(4)

In [514]:
for i in estate_url:
    driver.get(i)
    time.sleep(3)
    
    try:
        bhk_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bhk.append(bhk_detail.text[0:1])           
    except NoSuchElementException:
        Bhk.append(np.nan)
        

    try:
        bed_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[1]')
        Bed.append(bed_detail.text[0:1])
    except NoSuchElementException:
        Bed.append(np.nan)

    
    try:
        prop_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[2]/p')
        Property_Type.append(prop_detail.text[0:-9])      
    except NoSuchElementException:                 
        Property_Type.append(np.nan)
        
    try:
        bathroom_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[2]')
        Bathroom.append(bathroom_detail.text[0:1])
    except NoSuchElementException:
        Bathroom.append(np.nan)
        
    try:
        add_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1')
        Address.append(add_detail.text)            
    except NoSuchElementException:
        Address.append(np.nan)
        
    try:
        city_detail = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        City.append(city_detail.text[0:11])
    except NoSuchElementException:
        City.append(np.nan)

    try:
        state_details = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[3]/div[1]/h1/div[2]')
        State_code.append(state_details.text[-8:-6])
    except NoSuchElementException:
        State_code.append(np.nan)

    
    try:
        landmark = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[5]/div/div[1]/div/table/tbody/tr[1]/td[1]')
        Landmark.append(landmark.text)
    except NoSuchElementException:
        Landmark.append(np.nan)

    try:
        year = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[8]/div/div[2]')
        Year_Built.append(year.text)        
    except NoSuchElementException:
        Year_Built.append(np.nan)

    
    try:
        psq = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[4]/div[1]/section[3]/div[3]/div/div[6]/div/div[2]')
        Price_per_sqft.append(psq.text)
    except NoSuchElementException:
        Price_per_sqft.append(np.nan)
        
    try:
        total = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[2]/div/div[1]/p[2]')
        Buy_total_price.append(total.text[:-24])
    except NoSuchElementException:
        Buy_total_price.append(np.nan)
    try:
        carpetarea = driver.find_element(By.XPATH,'/html/body/div[1]/div/div/section/div[3]/div/div/div/div/div/div[1]/div[4]/ul/li[3]')
        Carpetarea.append(carpetarea.text)
    except NoSuchElementException:
        Carpetarea.append(np.nan)

In [515]:
driver.close()

In [534]:
len(Property_Type)

4320

In [535]:
# Creating the null list of the columns that were not present of the website 
Balcony = [np.nan]* 4320
Status = [np.nan]* 4320
Floor = [np.nan]* 4320
Transaction_type = [np.nan]* 4320
Furnished_status = [np.nan]* 4320
Facing = [np.nan]* 4320
Carparking = [np.nan]* 4320
Type_owner = [np.nan]* 4320
Booking_amt = [np.nan]* 4320

In [536]:
Country = ['United states'] * 4320

In [882]:
df = pd.DataFrame()

In [883]:
df["bhk"] = Bhk
df["property type"] = Property_Type
df["bed"] = Bed
df['bathroom'] = Bathroom
df["balcony"] = Balcony
df["address"] = Address
df["city"] = City
df["state code"] = State_code
df["country"] = Country
df["landmark"] = Landmark
df["carpet area"] = Carpetarea
df["status"] = Status
df["floor"] = Floor
df["transaction type"] = Transaction_type
df["year built"] = Year_Built
df["price per sqft"] = Price_per_sqft
df["furnished"] = Furnished_status
df["facing"] = Facing
df["car parking"] = Carparking
df["type of ownership"] = Type_owner
df["booling amount"] = Booking_amt
df["buy total price"] = Buy_total_price

In [884]:
df.head(30)

,bhk,property type,bed,bathroom,balcony,address,city,state code,country,landmark,carpet area,status,floor,transaction type,year built,price per sqft,furnished,facing,car parking,type of ownership,booling amount,buy total price
0,3,Mobile Home For Sale,3,2,NaN,"825 N Lamb Blvd, 118,\nLas Vegas, NV 89110",Las Vegas,NV,United states,Moore William K...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$92,900"
1,2,Condo For Sale,2,2,NaN,"5138 S Jones Boulevard, 206,\nLas Vegas, NV 89118",Las Vegas,NV,United states,Alamo Tony Elementary...,920 sqft,NaN,NaN,NaN,1989,$250,NaN,NaN,NaN,NaN,NaN,"$229,999"
2,1,Condo For Sale,1,1,NaN,"4670 Monterey Circle, 1,\nLas Vegas, NV 89169",Las Vegas,NV,United states,Paradise Prof Dev...,"1,000 sqft",NaN,NaN,NaN,1973,$235,NaN,NaN,NaN,NaN,NaN,"$235,000"
3,NaN,Land For Sale,NaN,NaN,NaN,"4924 E Washington Avenue,\nLas Vegas, NV 89110",Las Vegas,NV,United states,Earl Ira J...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$268,000"
4,3,House For Sale,3,2,NaN,"321 Beaumont Street,\nLas Vegas, NV 89106",Las Vegas,NV,United states,Wasden Howard Elementary...,"1,334 sqft",NaN,NaN,NaN,2592259,1955,NaN,NaN,NaN,NaN,NaN,"$270,000"
5,1,Condo For Sale,1,1,NaN,"91 E Agate Avenue, 401,\nLas Vegas, NV 89123",Las Vegas,NV,United states,Hummel John R...,786 sqft,NaN,NaN,NaN,2591790,2004,NaN,NaN,NaN,NaN,NaN,"$275,000"
6,2,Condo For Sale,2,2,NaN,"3411 Cactus Mountain Street, 101,\nLas Vegas, ...",Las Vegas,NV,United states,Conners Eileen Elementary...,"1,054 sqft",NaN,NaN,NaN,2004,$303,NaN,NaN,NaN,NaN,NaN,"$319,000"
7,3,House For Sale,3,2,NaN,"513 N Minnesota Street,\nLas Vegas, NV 89107",Las Vegas,NV,United states,McWilliams J T...,934 sqft,NaN,NaN,NaN,2592214,1956,NaN,NaN,NaN,NaN,NaN,"$320,000"
8,1,For Sale,1,1,NaN,"353 E Bonneville Avenue, 705,\nLas Vegas, NV 8...",Las Vegas,NV,United states,Park John S...,884 sqft,NaN,NaN,NaN,2589217,2008,NaN,NaN,NaN,NaN,NaN,"$325,000"
9,3,House For Sale,3,2,NaN,"4416 Rip Van Winkle Lane,\nLas Vegas, NV 89102",Las Vegas,NV,United states,Roundy Dr C...,"1,247 sqft",NaN,NaN,NaN,2585922,1976,NaN,NaN,NaN,NaN,NaN,"$330,000"
10,3,House For Sale,3,2,NaN,"2083 Seahurst Drive,\nLas Vegas, NV 89142",Las Vegas,NV,United states,Mendoza John F...,"1,377 sqft",NaN,NaN,NaN,2592250,1990,NaN,NaN,NaN,NaN,NaN,"$339,999"
11,2,Townhouse For Sale,2,3,NaN,"10178 Quilt Tree Street, None,\nLas Vegas, NV ...",Las Vegas,NV,United states,Hummel John R...,"1,284 sqft",NaN,NaN,NaN,2002,$265,NaN,NaN,NaN,NaN,NaN,"$340,000"
12,3,House For Sale,3,3,NaN,"5408 Bradford Pear Drive,\nLas Vegas, NV 89122",Las Vegas,NV,United states,NaN,"1,362 sqft",NaN,NaN,NaN,2007,$250,NaN,NaN,NaN,NaN,NaN,"$340,000"
13,3,Condo For Sale,3,2,NaN,"104 Breezy Tree Court, 201,\nLas Vegas, NV 89145",Las Vegas,NV,United states,Jacobson Walter Elementary...,"1,373 sqft",NaN,NaN,NaN,1998,$253,NaN,NaN,NaN,NaN,NaN,"$347,000"
14,3,House For Sale,3,2,NaN,"6509 Dinning Avenue,\nLas Vegas, NV 89107",Las Vegas,NV,United states,Adcock O K...,"1,354 sqft",NaN,NaN,NaN,2589717,1968,NaN,NaN,NaN,NaN,NaN,"$349,000"
15,3,House For Sale,3,2,NaN,"1005 Vernon Avenue,\nLas Vegas, NV 89108",Las Vegas,NV,United states,Twin Lakes Elementary...,"1,374 sqft",NaN,NaN,NaN,2562753,1954,NaN,NaN,NaN,NaN,NaN,"$350,000"
16,2,Condo For Sale,2,2,NaN,"6255 W Arby Avenue, 244,\nLas Vegas, NV 89118",Las Vegas,NV,United states,Alamo Tony Elementary...,"1,220 sqft",NaN,NaN,NaN,2004,$287,NaN,NaN,NaN,NaN,NaN,"$350,000"
17,3,Townhouse For Sale,3,3,NaN,"6955 HONOR HILL ST,\nLas Vegas, NV 89166",Las Vegas,NV,United states,Bozarth Henry &...,"1,309 sqft",NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,"$359,990"
18,3,Townhouse For Sale,3,3,NaN,"7925 Trea Avenue,\nLas Vegas, NV 89147",Las Vegas,NV,United states,Bryan Roger M...,"1,311 sqft",NaN,NaN,NaN,1994,$275,NaN,NaN,NaN,NaN,NaN,"$360,000"
19,1,For Sale,1,6,NaN,"4381 W Flamingo Road, 32306,\nLas Vegas, NV 89103",Las Vegas,NV,United states,Thiriot Joseph E...,NaN,NaN,NaN,NaN,NaN,2592160,NaN,NaN,NaN,NaN,NaN,"$368,000"
20,4,House For Sale,4,3,NaN,"5123 Mineral Lake Drive,\nLas Vegas, NV 89122",Las Vegas,NV,United states,Whitney Elementary School,"1,594 sqft",NaN,NaN,NaN,2002,$232,NaN,NaN,NaN,NaN,NaN,"$369,900"
21,3,Townhouse For Sale,3,3,NaN,"6917 STRATHAM HILL ST,\nLas Vegas, NV 89166",Las Vegas,NV,United states,Bozarth Henry &...,"1,410 sqft",NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,"$377,990"
22,3,Townhouse For Sale,3,3,NaN,"6959 HONOR HILL ST,\nLas Vegas, NV 89166",Las Vegas,NV,United states,Bozarth Henry &...,"1,410 sqft",NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,"$378,990"
23,3,Townhouse For Sale,3,3,NaN,"6968 STAFFORD HILL ST,\nLas Vegas, NV 89166",Las Vegas,NV,United states,Bozarth Henry &...,"1,430 sqft",NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,"$379,990"
24,3,Townhouse For Sale,3,3,NaN,"6912 STRATHAM HILL ST,\nLas Vegas, NV 89166",Las Vegas,NV,United states,Bozarth Henry &...,"1,410 sqft",NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,"$379,990"
25,3,House For Sale,3,3,NaN,"6621 Silver Penny Avenue,\nLas Vegas, NV 89108",Las Vegas,NV,United states,Bunker Berkeley L...,"1,472 sqft",NaN,NaN,NaN,1989,$258,NaN,NaN,NaN,NaN,NaN,"$380,000"
26,4,House For Sale,4,3,NaN,"3893 Rolling Cloud Drive,\nLas Vegas, NV 89115",Las Vegas,NV,United states,Woolley Gwendolyn Elementary...,"1,693 sqft",NaN,NaN,NaN,2591837,1994,NaN,NaN,NaN,NaN,NaN,"$384,899"
27,2,Condo For Sale,2,3,NaN,"5201 S Torrey Pines Drive, 1274,\nLas Vegas, N...",Las Vegas,NV,United states,Alamo Tony Elementary...,"1,467 sqft",NaN,NaN,NaN,1992,$265,NaN,NaN,NaN,NaN,NaN,"$388,500"
28,3,House For Sale,3,3,NaN,"7600 Almeria Avenue,\nLas Vegas, NV 89128",Las Vegas,NV,United states,Bryan Richard H...,"1,331 sqft",NaN,NaN,NaN,1994,$292,NaN,NaN,NaN,NaN,NaN,"$389,000"
29,3,Townhouse For Sale,3,3,NaN,"4537 Honey Hills Ave, Plan: 1437 Plan,\nLas Ve...",Las Vegas,NV,United states,Earl Ira J...,"1,437 sqft",NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,"$390,990"

In [885]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4320 entries, 0 to 4319
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   bhk                4162 non-null   object
 1   property type      4309 non-null   object
 2   bed                4162 non-null   object
 3   bathroom           4019 non-null   object
 4   balcony            0 non-null      float64
 5   address            4309 non-null   object
 6   city               4309 non-null   object
 7   state code         4309 non-null   object
 8   country            4320 non-null   object
 9   landmark           4251 non-null   object
 10  carpet area        3810 non-null   object
 11  status             0 non-null      float64
 12  floor              0 non-null      float64
 13  transaction type   0 non-null      float64
 14  year built         3978 non-null   object
 15  price per sqft     4123 non-null   object
 16  furnished          0 non-null      float64
 17  facing             0 non-null      float64
 18  car parking        0 non-null      float64
 19  type of ownership  0 non-null      float64
 20  booling amount     0 non-null      float64
 21  buy total price    4309 non-null   object
dtypes: float64(9), object(13)
memory usage: 742.6+ KB

In [886]:
df.duplicated().sum()

89

In [887]:
df.drop_duplicates()
df.head()

,bhk,property type,bed,bathroom,balcony,address,city,state code,country,landmark,carpet area,status,floor,transaction type,year built,price per sqft,furnished,facing,car parking,type of ownership,booling amount,buy total price
0,3,Mobile Home For Sale,3,2,NaN,"825 N Lamb Blvd, 118,\nLas Vegas, NV 89110",Las Vegas,NV,United states,Moore William K...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$92,900"
1,2,Condo For Sale,2,2,NaN,"5138 S Jones Boulevard, 206,\nLas Vegas, NV 89118",Las Vegas,NV,United states,Alamo Tony Elementary...,920 sqft,NaN,NaN,NaN,1989,$250,NaN,NaN,NaN,NaN,NaN,"$229,999"
2,1,Condo For Sale,1,1,NaN,"4670 Monterey Circle, 1,\nLas Vegas, NV 89169",Las Vegas,NV,United states,Paradise Prof Dev...,"1,000 sqft",NaN,NaN,NaN,1973,$235,NaN,NaN,NaN,NaN,NaN,"$235,000"
3,NaN,Land For Sale,NaN,NaN,NaN,"4924 E Washington Avenue,\nLas Vegas, NV 89110",Las Vegas,NV,United states,Earl Ira J...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$268,000"
4,3,House For Sale,3,2,NaN,"321 Beaumont Street,\nLas Vegas, NV 89106",Las Vegas,NV,United states,Wasden Howard Elementary...,"1,334 sqft",NaN,NaN,NaN,2592259,1955,NaN,NaN,NaN,NaN,NaN,"$270,000"

In [888]:
pd.set_option('display.max_columns',None)
df.head(30)

,bhk,property type,bed,bathroom,balcony,address,city,state code,country,landmark,carpet area,status,floor,transaction type,year built,price per sqft,furnished,facing,car parking,type of ownership,booling amount,buy total price
0,3,Mobile Home For Sale,3,2,NaN,"825 N Lamb Blvd, 118,\nLas Vegas, NV 89110",Las Vegas,NV,United states,Moore William K...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$92,900"
1,2,Condo For Sale,2,2,NaN,"5138 S Jones Boulevard, 206,\nLas Vegas, NV 89118",Las Vegas,NV,United states,Alamo Tony Elementary...,920 sqft,NaN,NaN,NaN,1989,$250,NaN,NaN,NaN,NaN,NaN,"$229,999"
2,1,Condo For Sale,1,1,NaN,"4670 Monterey Circle, 1,\nLas Vegas, NV 89169",Las Vegas,NV,United states,Paradise Prof Dev...,"1,000 sqft",NaN,NaN,NaN,1973,$235,NaN,NaN,NaN,NaN,NaN,"$235,000"
3,NaN,Land For Sale,NaN,NaN,NaN,"4924 E Washington Avenue,\nLas Vegas, NV 89110",Las Vegas,NV,United states,Earl Ira J...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$268,000"
4,3,House For Sale,3,2,NaN,"321 Beaumont Street,\nLas Vegas, NV 89106",Las Vegas,NV,United states,Wasden Howard Elementary...,"1,334 sqft",NaN,NaN,NaN,2592259,1955,NaN,NaN,NaN,NaN,NaN,"$270,000"
5,1,Condo For Sale,1,1,NaN,"91 E Agate Avenue, 401,\nLas Vegas, NV 89123",Las Vegas,NV,United states,Hummel John R...,786 sqft,NaN,NaN,NaN,2591790,2004,NaN,NaN,NaN,NaN,NaN,"$275,000"
6,2,Condo For Sale,2,2,NaN,"3411 Cactus Mountain Street, 101,\nLas Vegas, ...",Las Vegas,NV,United states,Conners Eileen Elementary...,"1,054 sqft",NaN,NaN,NaN,2004,$303,NaN,NaN,NaN,NaN,NaN,"$319,000"
7,3,House For Sale,3,2,NaN,"513 N Minnesota Street,\nLas Vegas, NV 89107",Las Vegas,NV,United states,McWilliams J T...,934 sqft,NaN,NaN,NaN,2592214,1956,NaN,NaN,NaN,NaN,NaN,"$320,000"
8,1,For Sale,1,1,NaN,"353 E Bonneville Avenue, 705,\nLas Vegas, NV 8...",Las Vegas,NV,United states,Park John S...,884 sqft,NaN,NaN,NaN,2589217,2008,NaN,NaN,NaN,NaN,NaN,"$325,000"
9,3,House For Sale,3,2,NaN,"4416 Rip Van Winkle Lane,\nLas Vegas, NV 89102",Las Vegas,NV,United states,Roundy Dr C...,"1,247 sqft",NaN,NaN,NaN,2585922,1976,NaN,NaN,NaN,NaN,NaN,"$330,000"
10,3,House For Sale,3,2,NaN,"2083 Seahurst Drive,\nLas Vegas, NV 89142",Las Vegas,NV,United states,Mendoza John F...,"1,377 sqft",NaN,NaN,NaN,2592250,1990,NaN,NaN,NaN,NaN,NaN,"$339,999"
11,2,Townhouse For Sale,2,3,NaN,"10178 Quilt Tree Street, None,\nLas Vegas, NV ...",Las Vegas,NV,United states,Hummel John R...,"1,284 sqft",NaN,NaN,NaN,2002,$265,NaN,NaN,NaN,NaN,NaN,"$340,000"
12,3,House For Sale,3,3,NaN,"5408 Bradford Pear Drive,\nLas Vegas, NV 89122",Las Vegas,NV,United states,NaN,"1,362 sqft",NaN,NaN,NaN,2007,$250,NaN,NaN,NaN,NaN,NaN,"$340,000"
13,3,Condo For Sale,3,2,NaN,"104 Breezy Tree Court, 201,\nLas Vegas, NV 89145",Las Vegas,NV,United states,Jacobson Walter Elementary...,"1,373 sqft",NaN,NaN,NaN,1998,$253,NaN,NaN,NaN,NaN,NaN,"$347,000"
14,3,House For Sale,3,2,NaN,"6509 Dinning Avenue,\nLas Vegas, NV 89107",Las Vegas,NV,United states,Adcock O K...,"1,354 sqft",NaN,NaN,NaN,2589717,1968,NaN,NaN,NaN,NaN,NaN,"$349,000"
15,3,House For Sale,3,2,NaN,"1005 Vernon Avenue,\nLas Vegas, NV 89108",Las Vegas,NV,United states,Twin Lakes Elementary...,"1,374 sqft",NaN,NaN,NaN,2562753,1954,NaN,NaN,NaN,NaN,NaN,"$350,000"
16,2,Condo For Sale,2,2,NaN,"6255 W Arby Avenue, 244,\nLas Vegas, NV 89118",Las Vegas,NV,United states,Alamo Tony Elementary...,"1,220 sqft",NaN,NaN,NaN,2004,$287,NaN,NaN,NaN,NaN,NaN,"$350,000"
17,3,Townhouse For Sale,3,3,NaN,"6955 HONOR HILL ST,\nLas Vegas, NV 89166",Las Vegas,NV,United states,Bozarth Henry &...,"1,309 sqft",NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,"$359,990"
18,3,Townhouse For Sale,3,3,NaN,"7925 Trea Avenue,\nLas Vegas, NV 89147",Las Vegas,NV,United states,Bryan Roger M...,"1,311 sqft",NaN,NaN,NaN,1994,$275,NaN,NaN,NaN,NaN,NaN,"$360,000"
19,1,For Sale,1,6,NaN,"4381 W Flamingo Road, 32306,\nLas Vegas, NV 89103",Las Vegas,NV,United states,Thiriot Joseph E...,NaN,NaN,NaN,NaN,NaN,2592160,NaN,NaN,NaN,NaN,NaN,"$368,000"
20,4,House For Sale,4,3,NaN,"5123 Mineral Lake Drive,\nLas Vegas, NV 89122",Las Vegas,NV,United states,Whitney Elementary School,"1,594 sqft",NaN,NaN,NaN,2002,$232,NaN,NaN,NaN,NaN,NaN,"$369,900"
21,3,Townhouse For Sale,3,3,NaN,"6917 STRATHAM HILL ST,\nLas Vegas, NV 89166",Las Vegas,NV,United states,Bozarth Henry &...,"1,410 sqft",NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,"$377,990"
22,3,Townhouse For Sale,3,3,NaN,"6959 HONOR HILL ST,\nLas Vegas, NV 89166",Las Vegas,NV,United states,Bozarth Henry &...,"1,410 sqft",NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,"$378,990"
23,3,Townhouse For Sale,3,3,NaN,"6968 STAFFORD HILL ST,\nLas Vegas, NV 89166",Las Vegas,NV,United states,Bozarth Henry &...,"1,430 sqft",NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,"$379,990"
24,3,Townhouse For Sale,3,3,NaN,"6912 STRATHAM HILL ST,\nLas Vegas, NV 89166",Las Vegas,NV,United states,Bozarth Henry &...,"1,410 sqft",NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,"$379,990"
25,3,House For Sale,3,3,NaN,"6621 Silver Penny Avenue,\nLas Vegas, NV 89108",Las Vegas,NV,United states,Bunker Berkeley L...,"1,472 sqft",NaN,NaN,NaN,1989,$258,NaN,NaN,NaN,NaN,NaN,"$380,000"
26,4,House For Sale,4,3,NaN,"3893 Rolling Cloud Drive,\nLas Vegas, NV 89115",Las Vegas,NV,United states,Woolley Gwendolyn Elementary...,"1,693 sqft",NaN,NaN,NaN,2591837,1994,NaN,NaN,NaN,NaN,NaN,"$384,899"
27,2,Condo For Sale,2,3,NaN,"5201 S Torrey Pines Drive, 1274,\nLas Vegas, N...",Las Vegas,NV,United states,Alamo Tony Elementary...,"1,467 sqft",NaN,NaN,NaN,1992,$265,NaN,NaN,NaN,NaN,NaN,"$388,500"
28,3,House For Sale,3,3,NaN,"7600 Almeria Avenue,\nLas Vegas, NV 89128",Las Vegas,NV,United states,Bryan Richard H...,"1,331 sqft",NaN,NaN,NaN,1994,$292,NaN,NaN,NaN,NaN,NaN,"$389,000"
29,3,Townhouse For Sale,3,3,NaN,"4537 Honey Hills Ave, Plan: 1437 Plan,\nLas Ve...",Las Vegas,NV,United states,Earl Ira J...,"1,437 sqft",NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,"$390,990"

In [889]:
df["property type"].value_counts()

property type
House                         2138
Condo                          427
                               416
Condo For Sale                 410
House For Sale                 315
Townhouse                      144
Townhouse For Sale             118
Land                           101
Duplex                          65
For Sale                        57
Duplex For Sale                 31
Multi-Family Home For Sale      22
Land For Sale                   17
Co-op For Sale                  15
Mobile Home                      8
Mobile Home For Sale             7
Apartment For Sale               7
Farm For Sale                    3
Co-op                            3
Apartment                        3
Farm                             2
Name: count, dtype: int64

In [890]:
df['property type'] = df['property type'].str.replace(' For Sale', '')

In [891]:
df.head()

,bhk,property type,bed,bathroom,balcony,address,city,state code,country,landmark,carpet area,status,floor,transaction type,year built,price per sqft,furnished,facing,car parking,type of ownership,booling amount,buy total price
0,3,Mobile Home,3,2,NaN,"825 N Lamb Blvd, 118,\nLas Vegas, NV 89110",Las Vegas,NV,United states,Moore William K...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$92,900"
1,2,Condo,2,2,NaN,"5138 S Jones Boulevard, 206,\nLas Vegas, NV 89118",Las Vegas,NV,United states,Alamo Tony Elementary...,920 sqft,NaN,NaN,NaN,1989,$250,NaN,NaN,NaN,NaN,NaN,"$229,999"
2,1,Condo,1,1,NaN,"4670 Monterey Circle, 1,\nLas Vegas, NV 89169",Las Vegas,NV,United states,Paradise Prof Dev...,"1,000 sqft",NaN,NaN,NaN,1973,$235,NaN,NaN,NaN,NaN,NaN,"$235,000"
3,NaN,Land,NaN,NaN,NaN,"4924 E Washington Avenue,\nLas Vegas, NV 89110",Las Vegas,NV,United states,Earl Ira J...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$268,000"
4,3,House,3,2,NaN,"321 Beaumont Street,\nLas Vegas, NV 89106",Las Vegas,NV,United states,Wasden Howard Elementary...,"1,334 sqft",NaN,NaN,NaN,2592259,1955,NaN,NaN,NaN,NaN,NaN,"$270,000"

In [892]:
df["property type"].value_counts()

property type
House                2453
Condo                 837
                      416
Townhouse             262
Land                  118
Duplex                 96
For Sale               57
Multi-Family Home      22
Co-op                  18
Mobile Home            15
Apartment              10
Farm                    5
Name: count, dtype: int64

In [893]:
df['property type'].isnull().any()

True

In [894]:
df['property type'].fillna('Condo', inplace=True)

In [895]:
df["property type"].value_counts()

property type
House                2453
Condo                 848
                      416
Townhouse             262
Land                  118
Duplex                 96
For Sale               57
Multi-Family Home      22
Co-op                  18
Mobile Home            15
Apartment              10
Farm                    5
Name: count, dtype: int64

In [896]:
df['address'] = df['address'].str.replace('\n', '')

In [897]:
df['city'] = df['city'].str.replace('INDIANAPOLIS', 'Indianapolis')
df['city'] = df['city'].str.replace('MIAMI', 'Miami')
df['city'] = df['city'].str.replace('LOS ANGELES', 'Los Angeles')
df['city'] = df['city'].str.replace('LOS ANGELES', 'Los Angeles')
df['city'] = df['city'].str.replace('HOUSTON', 'Houston')
df['city'] = df['city'].str.replace('SAN FRANCISCO', 'San Francisco')

In [898]:
df['city'].value_counts()

city
San Antonio      704
Indianapolis     491
Columbus         462
WASHINGTON       352
Miami            352
Chicago          352
Los Angeles      352
Phoenix          352
Las Vegas        329
San Francisco    321
Houston          242
Name: count, dtype: int64

In [899]:
df['carpet area'] = df['carpet area'].str.replace(',', '').str.replace(' sqft', '')

In [900]:
df['carpet area'] = pd.to_numeric(df['carpet area'], errors='coerce').astype('Int64')

In [901]:
df['carpet area'].dtype

Int64Dtype()

In [904]:
df['year built'] = pd.to_numeric(df['year built'], errors='coerce')
df['year built'] = np.where(df['year built'] == df['price per sqft'], df['price per sqft'], df['year built'])

In [906]:
df.head(10)

,bhk,property type,bed,bathroom,balcony,address,city,state code,country,landmark,carpet area,status,floor,transaction type,year built,price per sqft,furnished,facing,car parking,type of ownership,booling amount,buy total price
0,3,Mobile Home,3,2,NaN,"825 N Lamb Blvd, 118,Las Vegas, NV 89110",Las Vegas,NV,United states,Moore William K...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$92,900"
1,2,Condo,2,2,NaN,"5138 S Jones Boulevard, 206,Las Vegas, NV 89118",Las Vegas,NV,United states,Alamo Tony Elementary...,920,NaN,NaN,NaN,1989.0,$250,NaN,NaN,NaN,NaN,NaN,"$229,999"
2,1,Condo,1,1,NaN,"4670 Monterey Circle, 1,Las Vegas, NV 89169",Las Vegas,NV,United states,Paradise Prof Dev...,1000,NaN,NaN,NaN,1973.0,$235,NaN,NaN,NaN,NaN,NaN,"$235,000"
3,NaN,Land,NaN,NaN,NaN,"4924 E Washington Avenue,Las Vegas, NV 89110",Las Vegas,NV,United states,Earl Ira J...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$268,000"
4,3,House,3,2,NaN,"321 Beaumont Street,Las Vegas, NV 89106",Las Vegas,NV,United states,Wasden Howard Elementary...,1334,NaN,NaN,NaN,2592259.0,1955,NaN,NaN,NaN,NaN,NaN,"$270,000"
5,1,Condo,1,1,NaN,"91 E Agate Avenue, 401,Las Vegas, NV 89123",Las Vegas,NV,United states,Hummel John R...,786,NaN,NaN,NaN,2591790.0,2004,NaN,NaN,NaN,NaN,NaN,"$275,000"
6,2,Condo,2,2,NaN,"3411 Cactus Mountain Street, 101,Las Vegas, NV...",Las Vegas,NV,United states,Conners Eileen Elementary...,1054,NaN,NaN,NaN,2004.0,$303,NaN,NaN,NaN,NaN,NaN,"$319,000"
7,3,House,3,2,NaN,"513 N Minnesota Street,Las Vegas, NV 89107",Las Vegas,NV,United states,McWilliams J T...,934,NaN,NaN,NaN,2592214.0,1956,NaN,NaN,NaN,NaN,NaN,"$320,000"
8,1,For Sale,1,1,NaN,"353 E Bonneville Avenue, 705,Las Vegas, NV 89101",Las Vegas,NV,United states,Park John S...,884,NaN,NaN,NaN,2589217.0,2008,NaN,NaN,NaN,NaN,NaN,"$325,000"
9,3,House,3,2,NaN,"4416 Rip Van Winkle Lane,Las Vegas, NV 89102",Las Vegas,NV,United states,Roundy Dr C...,1247,NaN,NaN,NaN,2585922.0,1976,NaN,NaN,NaN,NaN,NaN,"$330,000"

In [907]:
df['year built'].fillna(0, inplace=True)
df['year built'] = df['year built'].astype(int)

In [908]:
df["buy total price"].count()

4309

In [909]:
df.shape

(4320, 22)

In [910]:
df["price per sqft"].fillna(0, inplace = True)

In [911]:
df['buy total price'] =  df['buy total price'].str.replace(",",'')

In [912]:
df['Numeric Value'] = df['buy total price'].str.replace('$', '').astype(float)

In [913]:
df['Numeric Value'].fillna(0, inplace=True)

In [914]:
df['Numeric Value'] = df['Numeric Value'].astype(int)

In [915]:
conversion_factor = 83.66
df['INR Value'] = df['Numeric Value'] * conversion_factor

In [916]:
df['Rounded INR'] = df['INR Value'].round().astype(int)

In [917]:
df.drop(columns=['Numeric Value', 'INR Value'], inplace=True)

In [918]:
df.drop(columns=['buy total price'], inplace=True)

In [919]:
df.rename(columns={'Rounded INR': 'buy total price'}, inplace=True)

In [920]:
df['year built'] = pd.to_numeric(df['year built'], errors='coerce')

In [921]:
df['year built'] = df['year built'].where((df['year built'] >= 1900) & (df['year built'] <= 2024))

In [922]:
df["year built"].mean()

1973.6698162729658

In [923]:
df['Numeric Value'] = df['price per sqft'].str.replace('$', '')

In [924]:
df["price p sqft"] = df["buy total price"] / df["carpet area"]

In [925]:
df["price p sqft"] = df["price p sqft"].round()

In [926]:
df["price per sqft"] = df["price per sqft"].str.replace("$",'')

In [927]:
df.head(

)

,bhk,property type,bed,bathroom,balcony,address,city,state code,country,landmark,carpet area,status,floor,transaction type,year built,price per sqft,furnished,facing,car parking,type of ownership,booling amount,buy total price,Numeric Value,price p sqft
0,3,Mobile Home,3,2,NaN,"825 N Lamb Blvd, 118,Las Vegas, NV 89110",Las Vegas,NV,United states,Moore William K...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7772014,NaN,<NA>
1,2,Condo,2,2,NaN,"5138 S Jones Boulevard, 206,Las Vegas, NV 89118",Las Vegas,NV,United states,Alamo Tony Elementary...,920,NaN,NaN,NaN,1989.0,250,NaN,NaN,NaN,NaN,NaN,19241716,250,20915.0
2,1,Condo,1,1,NaN,"4670 Monterey Circle, 1,Las Vegas, NV 89169",Las Vegas,NV,United states,Paradise Prof Dev...,1000,NaN,NaN,NaN,1973.0,235,NaN,NaN,NaN,NaN,NaN,19660100,235,19660.0
3,NaN,Land,NaN,NaN,NaN,"4924 E Washington Avenue,Las Vegas, NV 89110",Las Vegas,NV,United states,Earl Ira J...,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22420880,NaN,<NA>
4,3,House,3,2,NaN,"321 Beaumont Street,Las Vegas, NV 89106",Las Vegas,NV,United states,Wasden Howard Elementary...,1334,NaN,NaN,NaN,NaN,1955,NaN,NaN,NaN,NaN,NaN,22588200,1955,16933.0

In [928]:
df.drop(columns =["Numeric Value"],inplace = True)

In [929]:
df.drop(columns =["price per sqft"],inplace = True)

In [933]:
df['year built'].fillna(2000.0, inplace=True)

In [938]:
df.duplicated().sum()

264

In [939]:
df.drop_duplicates(inplace=True)

In [940]:
df.duplicated().sum()

0

In [941]:
df.head()

,bhk,property type,bed,bathroom,balcony,address,city,state code,country,landmark,carpet area,status,floor,transaction type,year built,furnished,facing,car parking,type of ownership,booling amount,buy total price,price p sqft
0,3,Mobile Home,3,2,NaN,"825 N Lamb Blvd, 118,Las Vegas, NV 89110",Las Vegas,NV,United states,Moore William K...,<NA>,NaN,NaN,NaN,2000.0,NaN,NaN,NaN,NaN,NaN,7772014,<NA>
1,2,Condo,2,2,NaN,"5138 S Jones Boulevard, 206,Las Vegas, NV 89118",Las Vegas,NV,United states,Alamo Tony Elementary...,920,NaN,NaN,NaN,1989.0,NaN,NaN,NaN,NaN,NaN,19241716,20915.0
2,1,Condo,1,1,NaN,"4670 Monterey Circle, 1,Las Vegas, NV 89169",Las Vegas,NV,United states,Paradise Prof Dev...,1000,NaN,NaN,NaN,1973.0,NaN,NaN,NaN,NaN,NaN,19660100,19660.0
3,NaN,Land,NaN,NaN,NaN,"4924 E Washington Avenue,Las Vegas, NV 89110",Las Vegas,NV,United states,Earl Ira J...,<NA>,NaN,NaN,NaN,2000.0,NaN,NaN,NaN,NaN,NaN,22420880,<NA>
4,3,House,3,2,NaN,"321 Beaumont Street,Las Vegas, NV 89106",Las Vegas,NV,United states,Wasden Howard Elementary...,1334,NaN,NaN,NaN,2000.0,NaN,NaN,NaN,NaN,NaN,22588200,16933.0

In [942]:
df.shape

(4056, 22)

In [943]:
df['serial number'] = range(1, len(df) + 1)

In [944]:
df = df[['serial number'] +list(df.columns[:-1])]

In [945]:
df.head()

,serial number,bhk,property type,bed,bathroom,balcony,address,city,state code,country,landmark,carpet area,status,floor,transaction type,year built,furnished,facing,car parking,type of ownership,booling amount,buy total price,price p sqft
0,1,3,Mobile Home,3,2,NaN,"825 N Lamb Blvd, 118,Las Vegas, NV 89110",Las Vegas,NV,United states,Moore William K...,<NA>,NaN,NaN,NaN,2000.0,NaN,NaN,NaN,NaN,NaN,7772014,<NA>
1,2,2,Condo,2,2,NaN,"5138 S Jones Boulevard, 206,Las Vegas, NV 89118",Las Vegas,NV,United states,Alamo Tony Elementary...,920,NaN,NaN,NaN,1989.0,NaN,NaN,NaN,NaN,NaN,19241716,20915.0
2,3,1,Condo,1,1,NaN,"4670 Monterey Circle, 1,Las Vegas, NV 89169",Las Vegas,NV,United states,Paradise Prof Dev...,1000,NaN,NaN,NaN,1973.0,NaN,NaN,NaN,NaN,NaN,19660100,19660.0
3,4,NaN,Land,NaN,NaN,NaN,"4924 E Washington Avenue,Las Vegas, NV 89110",Las Vegas,NV,United states,Earl Ira J...,<NA>,NaN,NaN,NaN,2000.0,NaN,NaN,NaN,NaN,NaN,22420880,<NA>
4,5,3,House,3,2,NaN,"321 Beaumont Street,Las Vegas, NV 89106",Las Vegas,NV,United states,Wasden Howard Elementary...,1334,NaN,NaN,NaN,2000.0,NaN,NaN,NaN,NaN,NaN,22588200,16933.0

In [946]:
#Sno,BHK type,Property Type, beds, bathroom, Balcony, Address,City,State code,Country ,Landmarks
df1 = pd.DataFrame()
df1["serial number"] = df["serial number"]
df1["bhk type"] = df["bhk"]
df1["property type"] = df["property type"]
df1["beds"] = df["bed"]
df1["bathroom"] = df["bathroom"]
df1["balocny"] = df["balcony"]
df1["address"] = df["address"]
df1["city"] = df["city"]
df1["state code"] =df["state code"]
df1["country"] = df["country"]
df1["landmark"] = df["landmark"]

In [948]:
df1.head()

,serial number,bhk type,property type,beds,bathroom,balocny,address,city,state code,country,landmark
0,1,3,Mobile Home,3,2,NaN,"825 N Lamb Blvd, 118,Las Vegas, NV 89110",Las Vegas,NV,United states,Moore William K...
1,2,2,Condo,2,2,NaN,"5138 S Jones Boulevard, 206,Las Vegas, NV 89118",Las Vegas,NV,United states,Alamo Tony Elementary...
2,3,1,Condo,1,1,NaN,"4670 Monterey Circle, 1,Las Vegas, NV 89169",Las Vegas,NV,United states,Paradise Prof Dev...
3,4,NaN,Land,NaN,NaN,NaN,"4924 E Washington Avenue,Las Vegas, NV 89110",Las Vegas,NV,United states,Earl Ira J...
4,5,3,House,3,2,NaN,"321 Beaumont Street,Las Vegas, NV 89106",Las Vegas,NV,United states,Wasden Howard Elementary...

In [949]:
df1.to_csv("table 1.csv",index = False)

In [956]:
#Sno, carpetarea,status ,floor ,transaction type, Year Built, price per square feet
df2  = pd.DataFrame()
df2["serial number"] = df["serial number"]
df2["carpet area"] = df["carpet area"]
df2["status"] = np.nan
df2["floor"] = df['floor']
df2["transaction type"] = df['transaction type']
df2["year built"] = df["year built"]
df2["price per sqft"] = df["price p sqft"]

In [957]:
df2.head()

,serial number,carpet area,status,floor,transaction type,year built,price per sqft
0,1,<NA>,NaN,NaN,NaN,2000.0,<NA>
1,2,920,NaN,NaN,NaN,1989.0,20915.0
2,3,1000,NaN,NaN,NaN,1973.0,19660.0
3,4,<NA>,NaN,NaN,NaN,2000.0,<NA>
4,5,1334,NaN,NaN,NaN,2000.0,16933.0

In [958]:
df2.to_csv("table_02.csv",index = False)

In [959]:
#Sno , furnished status, facing , Car Parking, Type of ownership ,booking amount ,buy total price
df3 = pd.DataFrame()
df3["serial number"] = df["serial number"]
df3["furnished status"]=df["furnished"]
df3["facing"] = np.nan
df3["car parking"] = df["car parking"]
df3["type of ownership"]  = df["type of ownership"]
df3["booking amount"] = df["booling amount"]
df3["buy total price"] = df["buy total price"]

df3.head()

,serial number,furnished status,facing,car parking,type of ownership,booking amount,buy total price
0,1,NaN,NaN,NaN,NaN,NaN,7772014
1,2,NaN,NaN,NaN,NaN,NaN,19241716
2,3,NaN,NaN,NaN,NaN,NaN,19660100
3,4,NaN,NaN,NaN,NaN,NaN,22420880
4,5,NaN,NaN,NaN,NaN,NaN,22588200

In [960]:
df3.to_csv("table_03.csv",index = False)